name: Upload go-tpc Results to Nyrkiö

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload-results:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to access the latest results file
      - uses: actions/checkout@v4

      # Check for results files and set output
      - name: Check for go-tpc results
        id: check-files
        run: |
          if ls load-test-results/results-*.txt >/dev/null 2>&1; then
            echo "Files found"
            echo "files_exist=true" >> $GITHUB_OUTPUT
          else
            echo "No results files found in load-test-results/, skipping workflow"
            echo "files_exist=false" >> $GITHUB_OUTPUT
          fi

      # Find the latest results file (only if files exist)
      - name: Find latest go-tpc results
        if: steps.check-files.outputs.files_exist == 'true'
        run: |
          LATEST_FILE=$(ls -t load-test-results/results-*.txt | head -n 1)
          echo "LATEST_FILE=$LATEST_FILE" >> $GITHUB_ENV

      # Analyze results with Nyrkiö (only if files exist)
      - name: Analyze go-tpc results with Nyrkiö
        if: steps.check-files.outputs.files_exist == 'true'
        uses: nyrkio/change-detection@v2
        with:
          tool: 'gotpc' 
          output-file-path: ${{ env.LATEST_FILE }}
          nyrkio-token: ${{ secrets.NYRKIO_JWT_TOKEN }}
